name: Create Release Branch
on:
  push:
      tags:
        - '*'

permissions:
    contents: write
    issues: write
    pull-requests: write     
              
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get last tag
      run: |
        echo git describe
         
    