name: Create Hotfix Branch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of hotfix'
        required: true

permissions:
    contents: write
    issues: write
    pull-requests: write     
              
jobs:
   createhotfix:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com  
    - name: Create hotfix branch
      run: git checkout -b hotfix/${{ github.event.inputs.name }}
    - name: Script
      run: |
         git log --pretty="- %s" > CHANGELOG.md
         cat CHANGELOG.md
   
    - name: Commit changes
      run: |
        touch filename.txt
        git add filename.txt
        git commit --message "Prepare hotfix ${{ github.event.inputs.name }}"
        git push origin hotfix/${{ github.event.inputs.name }}
    - name: Create pull request into develop
      uses: peter-evans/create-pull-request@v4
      id: cprdev
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: hotfix/${{ github.event.inputs.name }}
        base: develop
        title: v${{ github.event.inputs.name }} into develop
        labels: |
            develop
            hotfix-to-develop-pr
            automated pr
            customer-portal
            v${{ github.event.inputs.name }}
        body: |
           Hi!
           This PR was created in response workflow running to hotfix.
    - name: Check outputs
      if: ${{ steps.cprdev.outputs.pull-request-number }}
      run: |
         echo "Pull Request Number - ${{ steps.cprdev.outputs.pull-request-number }}"
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  
        ref: hotfix/${{ github.event.inputs.name }}
    - name: Commit changes
      run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
    - name: Create pull request into main
      uses: peter-evans/create-pull-request@v4
      id: cprmain
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/v${{ github.event.inputs.name }}
        base: main
        title: v${{ github.event.inputs.name }} into main
        labels: |
            main
            hotfix-to-develop-pr
            automated pr
            customer-portal
            v${{ github.event.inputs.name }}
        body: |
           Hi!
           This PR was created in response workflow running to hotfix.      
    - name: Check outputs
      if: ${{ steps.cprmain.outputs.pull-request-number }}
      run: |
         echo "Pull Request Number - ${{ steps.cprmain.outputs.pull-request-number }}"
