name: Create Release Branch
on:
  push:
      tags:
        - '*'

permissions:
    contents: write
    issues: write
    pull-requests: write     
              
jobs:
  createrelease:
    runs-on: ubuntu-latest
    outputs:
      TARGET_TAG: ${{ steps.init.outputs.TARGET_TAG }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Get last tag
        id: init
        run: |
          echo "TARGET_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
  check-tag:
    runs-on: ubuntu-latest
    needs: createrelease
    steps:
      - name: Print tag
        id: init
        run: echo ${{ needs.createrelease.outputs.TARGET_TAG }}
  create-branches:
    runs-on: ubuntu-latest
    needs: createrelease
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com  
    - name: Create release branch
      run: git checkout -b release/${{ needs.createrelease.outputs.TARGET_TAG }}
    - name: Script
      run: |
          git log --pretty="- %s" > CHANGELOG.md
          cat CHANGELOG.md
    
    - name: Commit changes
      run: |
        touch filename.txt
        git add filename.txt
        git commit --message "Prepare release ${{ needs.createrelease.outputs.TARGET_TAG }}"
        git push origin release/${{ needs.createrelease.outputs.TARGET_TAG }}
    - name: Create pull request into main
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/${{ needs.createrelease.outputs.TARGET_TAG }}
        base: main
        title: ${{ needs.createrelease.outputs.TARGET_TAG }} into main
        body: |
            Hi!
            This PR was created in response workflow running.
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
    - name: Create pull request into develop
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/${{ needs.createrelease.outputs.TARGET_TAG }}
        base: main
        title: ${{ needs.createrelease.outputs.TARGET_TAG }} into develop
        body: |
          Hi!
          This PR was created in response workflow running.      
            
    
            
