name: File changes
on:
   pull_request:
      branches:
        - test
jobs:
   activate-workflow:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3   
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          json: true
          base_sha: ${{ github.base_ref }}
      - name: List all changed files
        run: echo ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
   security-scan:
    name: Deploy to environment ${{ github.ref_name }} && ${{ github.ref_name != 'develop' }}
    needs: activate-workflow
    if: ${{ needs.activate-workflow.outputs.outputs.all_changed_files != '[]'}}
    strategy:
        matrix:
         artifact: ${{ fromJSON(needs.activate-workflow.outputs.outputs.all_changed_files) }}
    uses: ./.github/workflows/reusable-workflow.yml
    with:
        stage: ${{ github.ref_name }}
        resource: ${{ (matrix.artifact) }}       