name: File changes
on:
   pull_request:
      branches:
        - test
jobs:
   test-files:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3   
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          json: true
          base_sha: ${{ github.base_ref }}
      - name: List all changed files
        run: echo ${{ steps.changed-files-dir-names.outputs.all_changed_files }}