name: Quality feature build

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - test
permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      steps:
        - uses: hmarr/auto-approve-action@v2
          with:
            pull-request-number: ${{ github.event.pull_request.number }}
            review-message: "Auto approved automated PR"  
   auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    permissions:
      pull-requests: write
    steps: 
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.PAT }}         