name: Dispatcher workflow suite

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      resource:  
        required: false
        type: string
      java-version:
        required: false
        type: string
        default: '11'
      # allowing calling workflows to pass in maven parameter(s) such as '-Dmaven.test.skip' for certain apps, default to blank, not to skip test
      maven-params:
        required: false
        type: string
        default: ''  

jobs:
   deploy-lambda-project:
    name: Deploy to ${{ inputs.stage }} the lambda function ${{ inputs.resource }}
    runs-on: ubuntu-latest
    steps:
     - run: echo Build lambda image ${{ inputs.resource }}
   
