name: Check push on brach

on:
  push:
    branches:
      - test

jobs:

# Do something

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Print message
        run: echo ${{ github.ref_name }}  