name: Check push on brach

on:
  push:
    branches:
      - test
      - main
      - 'release*'

jobs:
# Do something

  deploy:
    runs-on: ubuntu-latest
    outputs:
        TARGET_ENV: ${{ steps.init.outputs.TARGET_ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Print message
        run: echo ${{ github.ref_name }}  
      - name: "Check where to deploy"
        id: init
        run: |
          if ${{ github.ref_name == 'test' }} 
          then
           echo "TARGET_ENV=develop" >> $GITHUB_OUTPUT 
          fi
          if ${{ github.ref_name == 'main' }}
          then
            echo "TARGET_ENV=production" >> $GITHUB_OUTPUT 
          else
            echo "TARGET_ENV=stage" >> $GITHUB_OUTPUT 
          fi
        
        shell: bash 
  check:
    name: Check stage
    needs: deploy
    runs-on: ubuntu-latest
    steps:
       - name: Print STAGE
         run: echo ${{ needs.deploy.outputs.TARGET_ENV }}       